/*************************************************************
  Download latest Blynk library here:
    https://github.com/blynkkk/blynk-library/releases/latest

  Blynk is a platform with iOS and Android apps to control
  Arduino, Raspberry Pi and the likes over the Internet.
  You can easily build graphic interfaces for all your
  projects by simply dragging and dropping widgets.

    Downloads, docs, tutorials: http://www.blynk.cc
    Sketch generator:           http://examples.blynk.cc
    Blynk community:            http://community.blynk.cc
    Follow us:                  http://www.fb.com/blynkapp
                                http://twitter.com/blynk_app

  Blynk library is licensed under MIT license
  This example code is in public domain.

 *************************************************************

  This example shows how to use ESP8266 Shield (with AT commands)
  to connect your project to Blynk.

  WARNING!
    It's very tricky to get it working. Please read this article:
    http://help.blynk.cc/hardware-and-libraries/arduino/esp8266-with-at-firmware

  Change WiFi ssid, pass, and Blynk auth token to run :)
  Feel free to apply it to any other example. It's simple!
 *************************************************************/

 /*
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMXk0MMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0ONMMMMMWXNMMMMMWOOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOOOkkkOOkOO000XXKNMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0ONMNOxxddxxdodO0Okddkdxkkk00XMKkKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKXXNWMMMMMMWXX0odOOdx00xxKXK0kxxxkk0KOxkxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMWNX0Okxdocccldk0NMMMMMWkdk00kdxO00OOO0O0OdddkKkxxkkxx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMWKkddoc:::cccccxOkxOXX0XWOddk00OOO0K0OkOxx0OxxkkxOKxx00ddK0KWMMMMMMMMMMMMWWNXKO000KXWMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMWXOdlcllllclodk00KWW0kkOOx0WxlxO00kkddkxxO0kOxk0kkxx00kkOOkokOONMMMMMMWNNX0kxdollcllclokXWMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMWKkdodOOkxOKXNWMMMMMMXkkkKMMMNdlO0OkO0OxoxkOkxk0KKX0k00kOkx0kxNMMMMMMWXOdddolcllcllldkkxdxKMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMWXK0xONMWWMMMMMMMMMMMMNkxk0WMMWXOkxdddllxxk0KOxkkkk0KK0OO0OkOxoKMMMMWKkdlcclollooxO00XWN0OxkXMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMXXNK0NMMMMMMMMMMMMMMMMWOkkONMNOOWMNXXKxoxOKOO0xdOOOOOkkO0kxkock0KWMN0kxdxkxxk0KXNWMMMMMMXOOx0WMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMNKXWKXMMMMMMMMMMMMMMWNX0xdxkXMWWWMMMMMMMNkodOOxk0KOkxoloodoll:dXOONNXK0O0NWNWMMMMMMMMMMMMXO0kONMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMXKNNKNMMMMMMMMMMWNKOkdoodddkKMMMMMMMMMMMMMXOkddkOOdllcc:;clcccOWMMWXNNKKWMMMMMMMMMMMMMMMMN00OkXMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMX0NK0NMMMWWNXXKOkdooxO0XKddkKMMMMMMMMKONMMMMMWXXNNX0OkxocllldKMMMMNXWWKXMMMMMMMMMMMMMMMMWX0OkxKMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMK0X0kOOkkxxdooddxO0XWMMMNkxk0WMMMMMMM0OWMMMMMMOkWMMMMMWKkxxlxXMMMWXXMNKNMMMMMMMMMMMMWNX0kdoood0MMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMKOK0oclldkO00KXNWMMMMMMMWOkkONMMMMMMMMMMMMMMMMNXMMMMMMMW00NNNMMMMWXNMXKWMMMMMMMMMWX0kdlloxxxkxOWMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMM0dkxlllcok0XXKKKNMMMMMMMM0kkONMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMNKXWK0WWNNXXK0Okdllodk0XWXOOkONMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWk::::llc::::;;ldOXNWWWMMMKkkkXMMMMMMMMMMMMMMMWWNWMMMMMMMMMMMMMMMMNKXN0xxdddolllooxk0XNMMMMN0OkkXMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWk:;,,;;;;;;;;;::clloddxxOkxkk0NNXXXNNNWWWWMMMW0xdxOKXXKXNNNWWWNNNXO0N0olloxO00KXNWMMMMMMMMW0OOxXMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWk:c;ck0OOkxxdolclc::;;;;::cloxkkxxxxdddxxxkkkkxocccclclllloddxxxxdoxOdokk0NMMMMMMMMMMMMMMMW0kkxKMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWk:c;oXMMMMMMMMWNXKOkxollcc:::cllooooolllllllccccccccccccccclllllllccc:dNMMMMMMMMMMMMMMMMMMMKkkx0MMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWk:c;oNMMMMMNKOkdddddxxxxxdolcclooddxxkkO0000OOkxkkkxdxxxdddoooolllccc:dNMMMMMMMMMMMMMMMMMMMXkOxOWMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWk:c;oNMWXOdooxk0KXNWWMMMWW0xkk0XXK00OOkkkO0KNWMMMMMMWMMMWWWWNNNNXOl:c:dNMMMMMMMMMMMMMMMMMMMNOOkkNMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWk:c;oK0dlokKWMMMMMMMMMMMMMXkOOXMMMMMMWWNX0kxdxk0XWMMMMMMMMMMMMMMMKl:c:dNMMMMMMMMMMMMMMMMMMMN0OkkXMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWxc:,:llxKWMMMMMMMMMMMMMMMMXOOOXMMMMMMMMMMMMWX0OxdxkKXNWMMMMMMMMMMKl:c:dNMMMMMMMMMMMMMMMMMMMWKOOxKMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWx::,:xXWMMMMMMMMMMMMMMMMMMNOOOKMMMMMMMMMMMMMMMMWX0kdodk0NWMMMMMMMKo:c:dNMMMMMMMMMMMMMMMMMMMMKOOxKMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWx:;;dNMMMMMMMMMMMMMMMMMMMMW0kk0WMMMMMMMMMMMMMMMMMMMNXKkddk0NMMMMMKlcc:dNMMMMMMMMMMMMMMMMMMMMXOOx0WMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWx::;dNMMMMMMMMMMMMMMMMMMMMW0kkONMMMMMMMMMMMMMMMMMMMMMMMNKkddkKWMMKo:c:dNMMMMMMMMMMMMMMMMMMMMN0OkOWMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWx:c:xWMMMMMMMMMMMMMMMMMMMMMKkkONMMMMMMMMMMMMMMMMMMMMMMMMMMN0xodOXKocc:dNMMMMMMMMMMMMMMMMMMMMN00kkNMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMNd:c:dNMMMMMMMMMMMMMMMMMMMMMXkkOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdooccc:dNMMMMMMMMMMMMMMMMMMMMWK0OkXMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMXocc:oXMMMMMMMMMMMMMMMMMMMMMXkkOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoccc:dNMMMMMMMMMMMMMMMMMMMMMX0OkKMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMWOdxdOWMMMMMMMMMMMMMMMMMWXK0OxxOKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKocc:dNMMMMMMMMMMMMMMMMMMMMMX0OkKMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMKO0OXMMMMMMMMMMMMMMWX0kxddxkxkk0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXocc:dNMMMMMMMMMMMMMMMMMMMMMN00k0WMMMMMMMMMMMMMMMMM
 MMMMMMMMMMM0O0OXMMMMMMMMMMWXKOxddxOKXWXOkk0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:c:dNMMMMMMMMMMMMMMMMMMMMMN00kOWMMMMMMMMMMMMMMMMM
 MMMMMMMMMMM0O0OXMMMMMMWX0OxddxOKXWMMMMW0kO0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0lllcoKMMMMMMMMMMMMMMMMMMMMMWK0OONMMMMMMMMMMMMMMMMM
 MMMMMMMMMMM0k0OXMMWNKOxooxOKXWMMMMMMMMW0xOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdooldXMMMMMMMMMMMMMMMMMMMWWN0OOkXMMMMMMMMMMMMMMMMM
 MMMMMMMMMMW0k0OKXOxoodk0XNMMMMMMMMMMMMMKkOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0OOx0MMMMMMMMMMMMMMMMWNKOkdddxxkKMMMMMMMMMMMMMMMMM
 MMMMMMMMMMM0k0kxoldOKNWMMMMMMMMMMMMMMMMXkOO0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KkKMMMMMMMMMMMMWNKOxolodkOkxxxKMMMMMMMMMMMMMMMMM
 MMMMMMMMMMW0k0kxx0NMMMMMMMMMMMMMMMMMMMMKolclKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KkKMMMMMMMMMWX0xolldk0XWMWKOOx0WMMMMMMMMMMMMMMMM
 MMMMMMMMMMW0k0OOKWMMMMMMMMMMMMMMMMMMMMMNkooxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KkKMMMMMWNKkdlcoxOKNMMMMMMX00kONMMMMMMMMMMMMMMMM
 MMMMMMMMMMW0k0k0NMMMMMMMMMMMMMMMMMMMMMMWKOOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0Kk0MMWX0xoclok0NWMMMMMMMMMX00kkNMMMMMMMMMMMMMMMM
 MMMMMMMMMMW0k0k0WMMMMMMMMMMMMMMMMMMMMMMMKOOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00k0X0xlcldOKNMMMMMMMMMMMMMN00OkXMMMMMMMMMMMMMMMM
 MMMMMMMMMMW0k0O0WMMMMMMMMMMMMMMMMMMMMMMMXOOOKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00kxxllxOXWMMMMMMMMMMMMMMMMWK00k0WMMMMMMMMMMMMMMM
 MMMMMMMMMMW0k0O0WMMMMMMMMMMMMMMMMMMMMMMMNOOO0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00kxxxKWMMMMMMMMMMMMMMMMMMMWOdxooXMMMMMMMMMMMMMMM
 MMMMMMMMMMMKO0O0WMMMMMMMMMMMMMMMMMMMMMMMN0OO0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00kkOXMMMMMMMMMMMMMMMMMMMMMW0xddxXMMMMMMMMMMMMMMM
 MMMMMMMMMMW0k0OKWMMMMMMMMMMMMMMMMMMMMMMMW0OOONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00kkXWMMMMMMMMMMMMMMMMMMMMMMN00OOXMMMMMMMMMMMMMMM 
 MMMMMMMMMMXxdxdOWMMMMMMMMMMMMMMMMMMMMMMMMKOOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00kkNMMMMMMMMMMMMMMMMMMMMMMMWK00OXMMMMMMMMMMMMMMM
 MMMMMMMMMMXdlolkNMMMMMMMMMMMMMMMMMMMMMMMMXOOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00kkNMMMMMMMMMMMMMMMMMMMMMMMWK00OKMMMMMMMMMMMMMMM
 MMMMMMMMMMWOk0OKMMMMMMMMMMMMMMMMMMMMMMMMMXOOOKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00kONMMMMMMMMMMMMMMMMMMMMMMMMX00OKWMMMMMMMMMMMMMM 
 MMMMMMMMMMWOO0OKMMMMMMMMMMMMMMMMMMMMMMMMMN0OO0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00kkNMMMMMMMMMMMMMMMMMMMMMMMMX0KO0WMMMMMMMMMMMMMM 
 MMMMMMMMMMWOO0OKMMMMMMMMMMMMMMMMMMMMMMMMMW0kO0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00kkNMMMMMMMMMMMMMMMMMMMMMMMMN00OONMMMMMMMMMMMMMM 
 MMMMMMMMMMWOO0OXMMMMMMMMMMMMMMMMMMMMMMMMMWKOkONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00k0WMMMMMMMMMMMMMMMMMMMMMMMMN000ONMMMMMMMMMMMMMM
 MMMMMMMMMMN0O0OXMMMMMMMMMMMMMMMMMMMMMMMMMMKOkOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkkOdkXMMMMMMMMMMMMMMMMMMMMMMMMWK00OXMMMMMMMMMMMMMM
 MMMMMMMMMMN0O0OXMMMMMMMMMMMMMMMMMMMMMMMMMMXOkkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdlocoKMMMMMMMMMMMMMMMMMMMMMMMMWK0KOKMMMMMMMMMMMMMM
 MMMMMMMMMMN0OK0XMMMMMMMMMMMMMMMMMMMMMMMMMMNOkkKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOkkxONMMMMMMMMMMMMMMMMMMMMMMMMMX0KOKWMMMMMMMMMMMMM
 MMMMMMMMMMN0O0OXMMMMMMMMMMMMMMMMMMMMMMMMMMXOdloKMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0KO0WMMMMMMMMMMMMMMMMMMMMMMMMMX0K00WMMMMMMMMMMMMM
 MMMMMMMMMMW0OKOXMMMMMMMMMMMMMMMMMMMMMMMMNOdl,':OMMMMMMMMMMMMMMMMMMMMMMMMMMMMN00KO0WMMMMMMMMMMMMMMMMMMMMMMMMMN0000NMMMMMMMMMMMMM
 MMMMMMMMMMW0O0OXMMMMMMMMMMMMMMMMMMMMMMMNx;;:ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMN00KO0WMMMMMMMMMMMMMMMMMMMMMMMMMN0000NMMMMMMMMMMMMM
 MMMMMMMMMMN0OKOXMMMMMMMMMMMMMMMMMMMMMMWNK00KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0KO0WMMMMMMMMMMMMMMMMMMMMMMMMMWK000XMMMMMMMMMMMMM
 MMMMMMMMWNKkO00XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KO0WMMMMMMMMMMMMMMMMMMMMMMMMMWX0K0XMMMMMMMMMMMMM
 MMMMMMN0xo:lO00XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KO0WMMMMMMMMMMMMMMMMMMMMMMMMMMX000KWMMMMMMMMMMMM
 MMMMWKdc:,.cO00XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KO0WMMMMMMMMMMMMMMMMMMMMMMMMMMN0000WMMMMMMMMMMMM
 MMMW0oll:. :OKO0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KO0WMMMMMMMMMMMMMMMMMMMMMMMMMMX0kolOWMMMMMMMMMMM
 MMMKdlc,. .:OKO0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KO0WMMMMMMMMMMMMMMMMMMMMMMMMWKxo;.;kWMMMMMMMMMMM
 MMWOll;. .:O0OKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KOKWMMMMMMMMMMMMMMMMMMMMMMMWOccoloKWMMMMMMMMMMMMM 
 MMWklc,. ..,dxOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KOKWMMMMMMMMMMMMMMMMMMMMMMWNXKKXXWMMMMMMMMMMMMMM 
 MMWOlc,.cc. .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KO0WMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMM
 MMMNxl:;:'.'lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00kOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMN0kdoox0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0OdxK0kkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0Odoolc::ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOxoll:,'..:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkdooc.....'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0dool,. ...'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0oll:......,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdll;......lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxol:.....;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOooc'...;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkol:;:oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM*/
 
#include "definitions.h" 

// define pinouts, define interrupts



// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "a2f791ce584c4b91a59bdc40e6e9b4d9";

// including the timer necessary instead of delays (so that blink can still run compatibly) 
BlynkTimer timer; 

// adding the wifi Manager
//WifiManager wifiManager; 

// Your WiFi credentials.
// Set password to "" for open networks.
char ssid[] = "iPhone";
char pass[] = "morecoffee";


ESP8266 wifi(&EspSerial);

void setup()
{
  // Debug console
  Serial.begin(9600);

  delay(10);

  // Set ESP8266 baud rate
  EspSerial.begin(ESP8266_BAUD);
  delay(10);

  // setting up function calls via the timer 
  // first argument is the duration between events in milliseconds 
  // up to 16 timers per timer object. 
  // max data sending rate of 10 values per second
  timer.setInterval(STATE_MACH_INTERVAL,StateMachine); // this is the timer that calls the state machine every STATE_MACH_INTERVAL miliseconds
  timer.setInterval(LED_INTERVAL,LEDMain); // can be on a separate time from the state machine if flashes must occur slower or faster 

  // WIFI Manager Attempts 
  // one-time thing: 
  //wifiManager.resetSettings(); 
  // setting up the auto connnect using WiFiManager Library
  //wifiManager.setConfigPortalTimeout(180); // waits 3 minutes and then will shut off. 
  //wifiManager.autoConnect("RemindME Walker","remindme"); 

  SetupLEDs(); 
  SetupRTCandSD();   
  SetupSensors(); 
  SetupButtonInterrupts(); 
  //Blynk.begin(auth, wifi, ssid, pass);
  SetupLEDDriveCurrents(); 
  ClearLED(); 
  DEBUG.println("Setup Complete!"); 
}

void loop()
{
  //Blynk.run();
  timer.run(); 
  if (rtc.updateTime() == false) //Updates the time variables from RTC
  {
    Serial.print("RTC failed to update");
  }
  // periodically checking 
  // currently disabled to prevent the SD card from preventing other operation of the device.
   
  // FIXME: maybe add a parameter that enables easier checking and initialization if possible
  if (!digitalRead(cardDetect))
  {
    if(CARD_OK == 1)
    {
      initializeCard();
    }
    else {
      initializeCard();   
    }
  }
  
}
